"""empty message

Revision ID: 301d1b230db5
Revises: 
Create Date: 2020-04-19 18:08:40.214150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301d1b230db5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.String(length=32), nullable=False),
    sa.Column('dt_creation', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('dt_archive', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('exam_hash', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('exercises', sa.String(), nullable=False),
    sa.Column('shuffle_exercises', sa.Boolean(), nullable=False),
    sa.Column('exam_duration', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('dt_creation', sa.DateTime(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('dt_archive', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('dt_subscription', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('dt_archive', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('exams')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('users')
    # ### end Alembic commands ###
