"""empty message

Revision ID: 74a2ff9eb5c9
Revises: ae40026b2605
Create Date: 2020-04-28 08:14:37.248279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a2ff9eb5c9'
down_revision = 'ae40026b2605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_tries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_username', sa.String(length=128), nullable=False),
    sa.Column('student_fullname', sa.String(length=128), nullable=False),
    sa.Column('student_picture', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_username', sa.String(length=128), nullable=False),
    sa.Column('teacher_fullname', sa.String(length=128), nullable=False),
    sa.Column('teacher_picture', sa.String(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('exam_hash', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('exercises', sa.String(), nullable=False),
    sa.Column('exam_duration', sa.Integer(), nullable=False),
    sa.Column('dt_try', sa.DateTime(), nullable=False),
    sa.Column('dt_expiration', sa.DateTime(), nullable=False),
    sa.Column('current_state', sa.Integer(), nullable=False),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('student_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_tries')
    # ### end Alembic commands ###
